version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: monitoring_service
      POSTGRES_USER: name
      POSTGRES_PASSWORD: name